-- MySQL Script generated by MySQL Workbench
-- Fri Jul 18 11:56:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bookstore_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookstore_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookstore_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bookstore_db` ;

-- -----------------------------------------------------
-- Table `bookstore_db`.`address`
-- Stores physical address details for customers and billing
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore_db`.`address` (
                                                        `address_id` INT NOT NULL AUTO_INCREMENT,
                                                        `city_name` VARCHAR(255) NOT NULL,
    `country_name` VARCHAR(255) NOT NULL,
    `postal_code` VARCHAR(255) NOT NULL,
    `state_code` VARCHAR(255) NOT NULL,
    `street_line` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`address_id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 2
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bookstore_db`.`admin`
-- Stores admin user credentials and metadata
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore_db`.`admin` (
                                                      `user_id` INT NOT NULL AUTO_INCREMENT,
                                                      `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                      `email` VARCHAR(100) NOT NULL,
    `first_name` VARCHAR(50) NOT NULL,
    `last_logged_in` DATETIME(6) NULL DEFAULT NULL,
    `last_logged_out` DATETIME(6) NULL DEFAULT NULL,
    `last_name` VARCHAR(50) NOT NULL,
    `password_hash` VARCHAR(255) NOT NULL,
    `role` ENUM('ADMIN') NOT NULL DEFAULT 'ADMIN',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`user_id`),
    UNIQUE INDEX `UKc0r9atamxvbhjjvy5j8da1kam` (`email` ASC) VISIBLE)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bookstore_db`.`book`
-- Stores information about books available for purchase
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore_db`.`book` (
                                                     `id` INT NOT NULL AUTO_INCREMENT,
                                                     `authors` VARCHAR(255) NULL DEFAULT NULL,
    `cover_image_url` VARCHAR(255) NULL DEFAULT NULL,
    `description` VARCHAR(255) NULL DEFAULT NULL,
    `genre` VARCHAR(255) NULL DEFAULT NULL,
    `isbn` VARCHAR(255) NULL DEFAULT NULL,
    `publisher` VARCHAR(255) NULL DEFAULT NULL,
    `sample_pdf_url` VARCHAR(255) NULL DEFAULT NULL,
    `title` VARCHAR(255) NULL DEFAULT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bookstore_db`.`customer`
-- Stores customer details and associated addresses
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore_db`.`customer` (
                                                         `user_id` INT NOT NULL,
                                                         `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                         `email` VARCHAR(100) NOT NULL,
    `first_name` VARCHAR(50) NOT NULL,
    `is_subscriber` BIT(1) NOT NULL,
    `last_logged_in` DATETIME(6) NULL DEFAULT NULL,
    `last_logged_out` DATETIME(6) NULL DEFAULT NULL,
    `last_name` VARCHAR(50) NOT NULL,
    `password_hash` VARCHAR(255) NOT NULL,
    `role` ENUM('ADMIN', 'CUSTOMER') NOT NULL,
    `status` ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED') NOT NULL,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `address_id` INT NULL DEFAULT NULL,
    PRIMARY KEY (`user_id`),
    UNIQUE INDEX `UKdwk6cx0afu8bs9o4t536v1j5v` (`email` ASC) VISIBLE,
    INDEX `FKglkhkmh2vyn790ijs6hiqqpi` (`address_id` ASC) VISIBLE,
    CONSTRAINT `FKglkhkmh2vyn790ijs6hiqqpi`
    FOREIGN KEY (`address_id`)
    REFERENCES `bookstore_db`.`address` (`address_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bookstore_db`.`book_promotion`
-- Stores promotional codes and related discount information
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore_db`.`book_promotion` (
                                                               `promotion_id` INT NOT NULL AUTO_INCREMENT,
                                                               `code` VARCHAR(6) NOT NULL,
    `details` TEXT NOT NULL,
    `discount` DECIMAL(5,2) NOT NULL,
    `valid_until` DATE NULL DEFAULT NULL,
    PRIMARY KEY (`promotion_id`),
    UNIQUE INDEX `UKeb81il1hbwfvs4g9rnlqav41a` (`code` ASC) VISIBLE)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bookstore_db`.`payment_card`
-- Stores customer payment card information
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore_db`.`payment_card` (
                                                             `card_id` INT NOT NULL AUTO_INCREMENT,
                                                             `encrypted_card_number` VARCHAR(100) NOT NULL,
    `encrypted_cvv` VARCHAR(100) NOT NULL,
    `expiration_date` DATE NOT NULL,
    `last_four_digits` VARCHAR(4) NOT NULL,
    `billing_address_id` INT NOT NULL,
    `customer_id` INT NOT NULL,
    PRIMARY KEY (`card_id`),
    INDEX `FK5a7rt88w3fhu93yy0eho7tnen` (`billing_address_id` ASC) VISIBLE,
    INDEX `FK7y58k5q46ft78j3xq58mcr07a` (`customer_id` ASC) VISIBLE,
    CONSTRAINT `FK5a7rt88w3fhu93yy0eho7tnen`
    FOREIGN KEY (`billing_address_id`)
    REFERENCES `bookstore_db`.`address` (`address_id`),
    CONSTRAINT `FK7y58k5q46ft78j3xq58mcr07a`
    FOREIGN KEY (`customer_id`)
    REFERENCES `bookstore_db`.`customer` (`user_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bookstore_db`.`book_order`
-- Stores customer orders and related information
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore_db`.`book_order` (
                                                           `order_id` INT NOT NULL AUTO_INCREMENT,
                                                           `is_refunded` BIT(1) NULL DEFAULT NULL,
    `order_date` DATETIME(6) NOT NULL,
    `shipping_fee` DECIMAL(10,2) NULL DEFAULT NULL,
    `customer_id` INT NOT NULL,
    `payment_card_id` INT NULL DEFAULT NULL,
    `promo_id` INT NULL DEFAULT NULL,
    PRIMARY KEY (`order_id`),
    INDEX `FKg9dfl5a6p0v1s3infwn0njds9` (`customer_id` ASC) VISIBLE,
    INDEX `FKtjd7stdkxbkbv6onq19t5lnrs` (`payment_card_id` ASC) VISIBLE,
    INDEX `FKm7d8l5uoftoi2a57qma840spg` (`promo_id` ASC) VISIBLE,
    CONSTRAINT `FKg9dfl5a6p0v1s3infwn0njds9`
    FOREIGN KEY (`customer_id`)
    REFERENCES `bookstore_db`.`customer` (`user_id`),
    CONSTRAINT `FKm7d8l5uoftoi2a57qma840spg`
    FOREIGN KEY (`promo_id`)
    REFERENCES `bookstore_db`.`book_promotion` (`promotion_id`),
    CONSTRAINT `FKtjd7stdkxbkbv6onq19t5lnrs`
    FOREIGN KEY (`payment_card_id`)
    REFERENCES `bookstore_db`.`payment_card` (`card_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bookstore_db`.`book_price`
-- Stores pricing information for books in different formats
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore_db`.`book_price` (
                                                           `format` ENUM('AUDIOBOOK', 'EBOOK', 'HARDCOVER', 'PAPERBACK') NOT NULL,
    `price` DECIMAL(38,2) NOT NULL,
    `format_type` ENUM('AUDIOBOOK', 'EBOOK', 'HARDCOVER', 'PAPERBACK') NOT NULL,
    `book_id` INT NOT NULL,
    PRIMARY KEY (`format`),
    INDEX `FK9wakmwpy6swlevvolsn25aq69` (`book_id` ASC) VISIBLE,
    CONSTRAINT `FK9wakmwpy6swlevvolsn25aq69`
    FOREIGN KEY (`book_id`)
    REFERENCES `bookstore_db`.`book` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bookstore_db`.`book_review`
-- Stores customer reviews for books
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore_db`.`book_review` (
                                                            `review_id` INT NOT NULL AUTO_INCREMENT,
                                                            `book_id` INT NOT NULL,
                                                            `rating` INT NOT NULL,
                                                            `review_text` TEXT NULL DEFAULT NULL,
                                                            `reviewer_name` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`review_id`),
    INDEX `FK29oatdl4f30mtg65oxo1nkmjg` (`book_id` ASC) VISIBLE,
    CONSTRAINT `FK29oatdl4f30mtg65oxo1nkmjg`
    FOREIGN KEY (`book_id`)
    REFERENCES `bookstore_db`.`book` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bookstore_db`.`order_item`
-- Stores individual items within an order
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore_db`.`order_item` (
                                                           `id` INT NOT NULL AUTO_INCREMENT,
                                                           `quantity` INT NOT NULL,
                                                           `unit_price` DECIMAL(38,2) NOT NULL,
    `book_id` INT NOT NULL,
    `order_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `FKb033an1f8qmpbnfl0a6jb5njs` (`book_id` ASC) VISIBLE,
    INDEX `FKpsi7jut8p2eombb9xuh51d5mn` (`order_id` ASC) VISIBLE,
    CONSTRAINT `FKb033an1f8qmpbnfl0a6jb5njs`
    FOREIGN KEY (`book_id`)
    REFERENCES `bookstore_db`.`book` (`id`),
    CONSTRAINT `FKpsi7jut8p2eombb9xuh51d5mn`
    FOREIGN KEY (`order_id`)
    REFERENCES `bookstore_db`.`book_order` (`order_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



